
import React from 'react';
import { AlertTriangle } from 'lucide-react';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';

const Disclaimer: React.FC = () => {
  return (
    <section id="disclaimer" className="py-16 md:py-24 bg-charcoal/30">
      <div className="container mx-auto px-4">
        <h2 className="text-3xl md:text-4xl font-bold text-center text-glow mb-6">
          Legal Disclaimer
        </h2>
        
        <div className="max-w-4xl mx-auto">
          <Alert className="mb-6 cyberpunk-card">
            <AlertTriangle className="h-5 w-5 text-amber-600" />
            <AlertTitle>Important Notice</AlertTitle>
            <AlertDescription className="text-light-gray/80">
              This service is provided for informational, educational, and research purposes only. Please read the following disclaimer carefully before using the Black History Matters Time Machine of Truth.
            </AlertDescription>
          </Alert>
          
          <div className="space-y-6 text-light-gray/80">
            <p>
              The Black History Matters Time Machine of Truth (referred to as "the Service") is an AI-powered educational and entertainment tool designed to provide immersive storytelling experiences related to Black history, African American culture, and the global African diaspora. The Service is guided by Dr. Martin Luther King Jr., Voice of the Dream, as an AI representation designed to provide historical education and moral guidance.
            </p>
            
            <h3 className="text-xl font-semibold text-primary-purple">Historical Content</h3>
            <p>
              While we strive for historical accuracy, the Service provides content for educational and entertainment purposes only. Users should consult academic sources, historical archives, and cultural institutions for comprehensive historical research. The Service makes reasonable efforts to present historically accurate information about Black history, but we do not guarantee the complete accuracy of all details presented. All historical narratives are researched and fact-checked to the best of our ability.
            </p>
            
            <h3 className="text-xl font-semibold text-primary-purple">Cultural Representation and Truth Mission</h3>
            <p>
              The Service aims to present Black history and African American culture with respect, authenticity, and truth. Our mission is to reveal hidden Black history that has been erased, distorted, or suppressed throughout history. We are committed to correcting historical wrongs and bringing understanding through truth. However, it is important to acknowledge that no AI system can fully capture the depth, complexity, and nuance of Black cultures and their rich histories. We encourage users to engage directly with Black historians, cultural centers, museums, and academic resources for more comprehensive understanding.
            </p>
            
            <h3 className="text-xl font-semibold text-primary-purple">The Test of Two Sacred Fates</h3>
            <p>
              Any content related to potential future scenarios is entirely speculative and presented for entertainment and educational purposes only. These scenarios do not constitute predictions, forecasts, or advice regarding future events. "The Test of the Sacred Times" feature is a spiritual and moral trial designed to encourage critical thinking about moral choices, resource stewardship, technology use, and global unity. These future scenarios are based on moral choices and consequence, designed to inspire reflection on how today's decisions affect tomorrow.
            </p>
            
            <h3 className="text-xl font-semibold text-primary-purple">4K Photorealistic Image Generation</h3>
            <p>
              Images generated by the Service are AI-created 4K photorealistic representations of historical and cultural content. These images are intended to enhance the storytelling experience and provide visual context for historical narratives. While created with attention to historical accuracy, these images should not be considered historically accurate reproductions or documentary evidence. All images are generated to avoid copyrighted elements and maintain historical authenticity.
            </p>
            
            <h3 className="text-xl font-semibold text-primary-purple">Limitation of Liability</h3>
            <p>
              AiWebTools.Ai and its affiliates shall not be liable for any direct, indirect, incidental, special, consequential, or exemplary damages resulting from your use of the Service or any content provided therein. By using the Service, you agree to indemnify and hold harmless AiWebTools.Ai and its affiliates from any claims arising from your use of the Service.
            </p>
            
            <h3 className="text-xl font-semibold text-primary-purple">User Responsibility and Educational Purpose</h3>
            <p>
              Users are responsible for their use of the Service and should exercise critical thinking when consuming any historical or cultural content. The Service is designed for education, research, and moral awakening, not as a substitute for professional research or consultation with historical experts. This tool was created to correct the wrongs of the past and bring unity and understanding to a world desperately in need of moral compass and historical truth.
            </p>
            
            <p className="font-semibold">
              By using the Black History Matters Time Machine of Truth, you acknowledge that you have read, understood, and agree to be bound by this disclaimer. You understand this is an educational tool designed to reveal hidden Black history and inspire moral awakening through truth.
            </p>
            
            <div className="mt-8 p-4 bg-primary-purple/10 rounded-lg border border-primary-purple/20">
              <p className="text-center text-light-gray/80 font-medium">
                For informational, educational, and research purposes only.
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Disclaimer;
